spring:
  application:
    name: ENTRY_POINT

server:
  port: 9000

eureka:
  server:
    maxThreadsForPeerReplication: 0
  instance:
    hostname: entry-eureka-server.kz
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/
